services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: db_postgres
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=1234567
      - POSTGRESQL_DATABASE=api-vendas
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/bitnami/postgresql
volumes:
  postgres_data:
    driver: local
